version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auth
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-vol:/var/lib/mysql

volumes:
  mysql-vol:
    driver: local